# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historicaldata', '0002_entity_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='legacy_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
