# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 23:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historicaldata', '0003_event_legacy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityBorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('area', models.BigIntegerField(blank=True, null=True)),
                ('perimeter', models.BigIntegerField(blank=True, null=True)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('label_rank', models.IntegerField(blank=True, null=True)),
                ('label_poz', django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='historicaldata.Entity')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='historicaldata.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Demographics',
            new_name='EntityDemographics',
        ),
        migrations.RenameModel(
            old_name='GDP',
            new_name='EntityGDP',
        ),
        migrations.RenameModel(
            old_name='Government',
            new_name='EntityGovernment',
        ),
        migrations.AlterUniqueTogether(
            name='border',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='border',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='border',
            name='event',
        ),
        migrations.RemoveField(
            model_name='border',
            name='source',
        ),
        migrations.AlterField(
            model_name='source',
            name='meta_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='historicaldata.MetaSource'),
        ),
        migrations.AlterUniqueTogether(
            name='entitylanguage',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='ethnicdemographic',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='religiondemographic',
            unique_together=set([]),
        ),
        migrations.DeleteModel(
            name='Border',
        ),
        migrations.AddField(
            model_name='entityborder',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='historicaldata.Source'),
        ),
        migrations.AlterUniqueTogether(
            name='entityborder',
            unique_together=set([('entity', 'event')]),
        ),
    ]
